name: tapkit
description: Calculator, Notes & QR Scanner â€” all in one tap.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # QR Scanner
  mobile_scanner: ^5.2.3
  
  # Utilities
  url_launcher: ^6.2.2
  intl: ^0.18.1
  flutter_animate: ^4.5.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  package_info_plus: ^8.0.1
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

